name: Koujousenplugin
version: ${project.version}
main: com.koujousen.plugin.koujousenplugin.Koujousenplugin
api-version: 1.16
commands:
  kjs:
    usage: /<Command>
    description: configure koujousen
